name = "MriReconstructionToolbox"
uuid = "5999b5f3-4ffc-4695-817d-461c6e99e3c0"
version = "0.1.0"
authors = ["Tamas Hakkel <hakkelt@gmail.com>"]

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FFTWOperators = "c59a084b-ba08-4f3f-af9e-f4298d6caa94"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
ImageGeoms = "9ee76f2b-840d-4475-b6d6-e485c9297852"
ImagePhantoms = "71a99df6-f52c-4da1-bd2a-69d6f37f3252"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
NFFTOperators = "35a93202-2abf-4a13-bc94-0aee2f861ee0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalCore = "dc4f5ac2-75d1-4f31-931e-60435d74994b"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructuredOptimization = "46cd3e9d-64ff-517d-a929-236bc1a1fc9d"
WaveletOperators = "f3582904-6f60-4bbd-985d-55eab799bc9d"

[sources]
AbstractOperators = {url = "https://github.com/hakkelt/AbstractOperators.jl"}
FFTWOperators = {url = "https://github.com/hakkelt/AbstractOperators.jl", subdir = "FFTWOperators"}
NFFTOperators = {url = "https://github.com/hakkelt/AbstractOperators.jl", subdir = "NFFTOperators"}
ProximalAlgorithms = {url = "https://github.com/hakkelt/ProximalAlgorithms.jl"}
ProximalCore = {url = "https://github.com/hakkelt/ProximalCore.jl"}
ProximalOperators = {url = "https://github.com/hakkelt/ProximalOperators.jl"}
StructuredOptimization = {url = "https://github.com/hakkelt/StructuredOptimization.jl"}
WaveletOperators = {url = "https://github.com/hakkelt/AbstractOperators.jl", subdir = "WaveletOperators"}

[compat]
ArgCheck = "2.5.0"
FastBroadcast = "0.3.5"
ImageGeoms = "0.11.1"
ImagePhantoms = "0.8.1"
LinearAlgebra = "1.11.0"
LinearMaps = "3.11.4"
NamedDims = "1.2.3"
Printf = "1.11.0"
Reexport = "1.2.2"
Statistics = "1.11.1"
StatsBase = "0.34.6"
Test = "1.11.0"
Wavelets = "0.10.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[targets]
test = ["Test", "Wavelets"]
