name = "docs"
version = "0.1.0"

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FFTWOperators = "c59a084b-ba08-4f3f-af9e-f4298d6caa94"
MIRTjim = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalCore = "dc4f5ac2-75d1-4f31-931e-60435d74994b"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StructuredOptimization = "46cd3e9d-64ff-517d-a929-236bc1a1fc9d"
WaveletOperators = "f3582904-6f60-4bbd-985d-55eab799bc9d"

[sources]
AbstractOperators = {url = "https://github.com/hakkelt/AbstractOperators.jl"}
FFTWOperators = {subdir = "FFTWOperators", url = "https://github.com/hakkelt/AbstractOperators.jl"}
ProximalAlgorithms = {url = "https://github.com/hakkelt/ProximalAlgorithms.jl"}
ProximalCore = {url = "https://github.com/hakkelt/ProximalCore.jl"}
ProximalOperators = {url = "https://github.com/hakkelt/ProximalOperators.jl"}
StructuredOptimization = {url = "https://github.com/hakkelt/StructuredOptimization.jl"}
WaveletOperators = {subdir = "WaveletOperators", url = "https://github.com/hakkelt/AbstractOperators.jl"}
